"""empty message

Revision ID: eebcf1300240
Revises: 0fdfad3683dd
Create Date: 2022-06-09 01:09:48.504081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebcf1300240'
down_revision = '0fdfad3683dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('beds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'beds')
    # ### end Alembic commands ###
